[package]

name = "libnotify"
version = "0.0.1"
authors = ["Mika Attila <radiantstatue@gmail.com>"]

[dependencies.libnotify-sys]
git = "https://github.com/crumblingstatue/rust-libnotify-sys.git"

[dependencies.glib-2_0-sys]
git = "https://github.com/crumblingstatue/glib-sys.git"
branch = "integ"
