[package]

name = "libnotify"
version = "0.4.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]
license = "MIT"
description = "Rust bindings to libnotify"
readme = "README.md"
repository = "https://github.com/crumblingstatue/rust-libnotify"
documentation = "http://crumblingstatue.github.io/doc/libnotify/libnotify/"
keywords = ["libnotify", "notification"]

[dependencies]
libnotify-sys = "^0.5.0"
glib-sys = "^0.3.4"
gtypes = "^0.2.0"
glib = "^0.1.3"
