[package]

name = "libnotify"
version = "0.3.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]
license = "MIT"
description = "Rust bindings to libnotify"
readme = "README.md"
repository = "https://github.com/crumblingstatue/rust-libnotify"
documentation = "http://crumblingstatue.github.io/doc/libnotify/libnotify/"
keywords = ["libnotify", "notification"]

[dependencies]
libnotify-sys = "0.3"
glib-2-0-sys = "0.46.0"
gtypes = "0.2"
