[build-dependencies]
pkg-config = ">=0.3.7"

[dependencies]
bitflags = "^0.9.0"
libc = "^0.2.0"

[dependencies.gdk-pixbuf-sys]
git = "https://github.com/gtk-rs/sys"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/sys"

[lib]
name = "libnotify_sys"

[package]
build = "build.rs"
links = "libnotify"
name = "libnotify-sys"
version = "1.0.0"

